version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/econominhas

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/econominhas
    pattern: "**"
    owner: ubuntu
    mode: 777
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: scripts/cd-stop.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/cd-prepare.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/cd-start.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/cd-validate.sh
      timeout: 300
      runas: ubuntu
