name: dbdocs-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - "*.dbml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Validate dbdocs
        run: dbdocs validate ./database.dbml
