name: openapi-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - 'openapi/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install redocly
        run: yarn add -D redocly

      - name: Validate openapi
        run: yarn openapi:lint
